version: '3.2'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27017:27017'
    env_file:
      - .env
  app:
    build: ./docker/app
    container_name: app
    ports:
      - '8000:8000'
    env_file:
      - .env
    command: uvicorn main:app --host 0.0.0.0 --reload 
